// Copyright (C) 2022 Jérôme "Lynix" Leclercq (lynix680@gmail.com)
// This file is part of the "Nazara Shading Language" project
// For conditions of distribution and use, see copyright notice in Config.hpp

// no header guards

#if !defined(NZSL_SHADERAST_NODE) && !defined(NZSL_SHADERAST_EXPRESSION) && !defined(NZSL_SHADERAST_STATEMENT)
#error You must define NZSL_SHADERAST_NODE or NZSL_SHADERAST_EXPRESSION or NZSL_SHADERAST_STATEMENT before including this file
#endif

#ifndef NZSL_SHADERAST_NODE
#define NZSL_SHADERAST_NODE(X)
#endif

#ifndef NZSL_SHADERAST_NODE_LAST
#define NZSL_SHADERAST_NODE_LAST(X)
#endif

#ifndef NZSL_SHADERAST_EXPRESSION
#define NZSL_SHADERAST_EXPRESSION(X) NZSL_SHADERAST_NODE(X)
#endif

#ifndef NZSL_SHADERAST_STATEMENT
#define NZSL_SHADERAST_STATEMENT(X) NZSL_SHADERAST_NODE(X)
#endif

#ifndef NZSL_SHADERAST_STATEMENT_LAST
#define NZSL_SHADERAST_STATEMENT_LAST(X) NZSL_SHADERAST_STATEMENT(X)
#endif

NZSL_SHADERAST_EXPRESSION(AccessIdentifierExpression)
NZSL_SHADERAST_EXPRESSION(AccessIndexExpression)
NZSL_SHADERAST_EXPRESSION(AliasValueExpression)
NZSL_SHADERAST_EXPRESSION(AssignExpression)
NZSL_SHADERAST_EXPRESSION(BinaryExpression)
NZSL_SHADERAST_EXPRESSION(CallFunctionExpression)
NZSL_SHADERAST_EXPRESSION(CallMethodExpression)
NZSL_SHADERAST_EXPRESSION(CastExpression)
NZSL_SHADERAST_EXPRESSION(ConditionalExpression)
NZSL_SHADERAST_EXPRESSION(ConstantExpression)
NZSL_SHADERAST_EXPRESSION(ConstantValueExpression)
NZSL_SHADERAST_EXPRESSION(FunctionExpression)
NZSL_SHADERAST_EXPRESSION(IdentifierExpression)
NZSL_SHADERAST_EXPRESSION(IntrinsicExpression)
NZSL_SHADERAST_EXPRESSION(IntrinsicFunctionExpression)
NZSL_SHADERAST_EXPRESSION(StructTypeExpression)
NZSL_SHADERAST_EXPRESSION(SwizzleExpression)
NZSL_SHADERAST_EXPRESSION(TypeExpression)
NZSL_SHADERAST_EXPRESSION(VariableValueExpression)
NZSL_SHADERAST_EXPRESSION(UnaryExpression)
NZSL_SHADERAST_STATEMENT(BranchStatement)
NZSL_SHADERAST_STATEMENT(ConditionalStatement)
NZSL_SHADERAST_STATEMENT(DeclareAliasStatement)
NZSL_SHADERAST_STATEMENT(DeclareConstStatement)
NZSL_SHADERAST_STATEMENT(DeclareExternalStatement)
NZSL_SHADERAST_STATEMENT(DeclareFunctionStatement)
NZSL_SHADERAST_STATEMENT(DeclareOptionStatement)
NZSL_SHADERAST_STATEMENT(DeclareStructStatement)
NZSL_SHADERAST_STATEMENT(DeclareVariableStatement)
NZSL_SHADERAST_STATEMENT(DiscardStatement)
NZSL_SHADERAST_STATEMENT(ForStatement)
NZSL_SHADERAST_STATEMENT(ForEachStatement)
NZSL_SHADERAST_STATEMENT(ExpressionStatement)
NZSL_SHADERAST_STATEMENT(ImportStatement)
NZSL_SHADERAST_STATEMENT(MultiStatement)
NZSL_SHADERAST_STATEMENT(NoOpStatement)
NZSL_SHADERAST_STATEMENT(ReturnStatement)
NZSL_SHADERAST_STATEMENT(ScopedStatement)
NZSL_SHADERAST_STATEMENT_LAST(WhileStatement)

#undef NZSL_SHADERAST_EXPRESSION
#undef NZSL_SHADERAST_NODE
#undef NZSL_SHADERAST_NODE_LAST
#undef NZSL_SHADERAST_STATEMENT
#undef NZSL_SHADERAST_STATEMENT_LAST
