// Copyright (C) 2023 Jérôme "Lynix" Leclercq (lynix680@gmail.com)
// This file is part of the "Nazara Shading Language" project
// For conditions of distribution and use, see copyright notice in Config.hpp

// no header guards

#if !defined(NZSL_SHADERAST_NODE) && !defined(NZSL_SHADERAST_EXPRESSION) && !defined(NZSL_SHADERAST_STATEMENT)
#error You must define NZSL_SHADERAST_NODE or NZSL_SHADERAST_EXPRESSION or NZSL_SHADERAST_STATEMENT before including this file
#endif

#ifndef NZSL_SHADERAST_NODE
#define NZSL_SHADERAST_NODE(X, C)
#endif

#ifndef NZSL_SHADERAST_NODE_LAST
#define NZSL_SHADERAST_NODE_LAST(X, C)
#endif

#ifndef NZSL_SHADERAST_EXPRESSION
#define NZSL_SHADERAST_EXPRESSION(X) NZSL_SHADERAST_NODE(X, Expression)
#endif

#ifndef NZSL_SHADERAST_STATEMENT
#define NZSL_SHADERAST_STATEMENT(X) NZSL_SHADERAST_NODE(X, Statement)
#endif

#ifndef NZSL_SHADERAST_STATEMENT_LAST
#define NZSL_SHADERAST_STATEMENT_LAST(X) NZSL_SHADERAST_STATEMENT(X)
#endif

NZSL_SHADERAST_EXPRESSION(AccessIdentifier)
NZSL_SHADERAST_EXPRESSION(AccessIndex)
NZSL_SHADERAST_EXPRESSION(AliasValue)
NZSL_SHADERAST_EXPRESSION(Assign)
NZSL_SHADERAST_EXPRESSION(Binary)
NZSL_SHADERAST_EXPRESSION(CallFunction)
NZSL_SHADERAST_EXPRESSION(CallMethod)
NZSL_SHADERAST_EXPRESSION(Cast)
NZSL_SHADERAST_EXPRESSION(Conditional)
NZSL_SHADERAST_EXPRESSION(Constant)
NZSL_SHADERAST_EXPRESSION(ConstantArrayValue)
NZSL_SHADERAST_EXPRESSION(ConstantValue)
NZSL_SHADERAST_EXPRESSION(Function)
NZSL_SHADERAST_EXPRESSION(Identifier)
NZSL_SHADERAST_EXPRESSION(Intrinsic)
NZSL_SHADERAST_EXPRESSION(IntrinsicFunction)
NZSL_SHADERAST_EXPRESSION(StructType)
NZSL_SHADERAST_EXPRESSION(Swizzle)
NZSL_SHADERAST_EXPRESSION(Type)
NZSL_SHADERAST_EXPRESSION(VariableValue)
NZSL_SHADERAST_EXPRESSION(Unary)
NZSL_SHADERAST_STATEMENT(Branch)
NZSL_SHADERAST_STATEMENT(Break)
NZSL_SHADERAST_STATEMENT(Conditional)
NZSL_SHADERAST_STATEMENT(Continue)
NZSL_SHADERAST_STATEMENT(DeclareAlias)
NZSL_SHADERAST_STATEMENT(DeclareConst)
NZSL_SHADERAST_STATEMENT(DeclareExternal)
NZSL_SHADERAST_STATEMENT(DeclareFunction)
NZSL_SHADERAST_STATEMENT(DeclareOption)
NZSL_SHADERAST_STATEMENT(DeclareStruct)
NZSL_SHADERAST_STATEMENT(DeclareVariable)
NZSL_SHADERAST_STATEMENT(Discard)
NZSL_SHADERAST_STATEMENT(For)
NZSL_SHADERAST_STATEMENT(ForEach)
NZSL_SHADERAST_STATEMENT(Expression)
NZSL_SHADERAST_STATEMENT(Import)
NZSL_SHADERAST_STATEMENT(Multi)
NZSL_SHADERAST_STATEMENT(NoOp)
NZSL_SHADERAST_STATEMENT(Return)
NZSL_SHADERAST_STATEMENT(Scoped)
NZSL_SHADERAST_STATEMENT_LAST(While)

#undef NZSL_SHADERAST_EXPRESSION
#undef NZSL_SHADERAST_NODE
#undef NZSL_SHADERAST_NODE_LAST
#undef NZSL_SHADERAST_STATEMENT
#undef NZSL_SHADERAST_STATEMENT_LAST
